FROM debezium/connect:1.6.0.Final

COPY confluentinc-kafka-connect-jdbc-10.2.0/lib $KAFKA_CONNECT_PLUGINS_DIR/confluentinc-kafka-connect-jdbc-10.2.0

# FROM confluentinc/cp-kafka-connect-base:6.0.1

# RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.2.0